# Generated by Django 3.2.7 on 2024-02-13 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('employee', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('pid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=255)),
                ('abbreviation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tt.employee')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tt.team')),
            ],
        ),
        migrations.CreateModel(
            name='Manage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tt.project')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tt.work')),
            ],
        ),
    ]
