# Generated by Django 3.2.7 on 2024-02-14 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manage',
            old_name='project',
            new_name='empid',
        ),
        migrations.RenameField(
            model_name='manage',
            old_name='work',
            new_name='pid',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='emp',
            new_name='empid',
        ),
        migrations.RemoveField(
            model_name='work',
            name='team',
        ),
    ]
